### ISSUE TITLE
Unable to start the docker container

### ISSUE THREAD

**Issue by lettore** [githubcdr/docker-mycontroller#6]
I used your image for a long time, but at the moment i'm unable to start succesfully the container.
This is the log:
SSLsocket creation:  java.io.IOException: java.security.ProviderException: Could not initialize NSS
java.io.IOException: java.security.ProviderException: Could not initialize NSS
	at Acme.Serve.SSLAcceptor.init(SSLAcceptor.java:187)
	at Acme.Serve.Serve.createAcceptor(Serve.java:912)
	at Acme.Serve.Serve.init(Serve.java:769)
	at Acme.Serve.Serve.runInBackground(Serve.java:649)
	at org.jboss.resteasy.plugins.server.tjws.TJWSServletServer.start(TJWSServletServer.java:179)
	at org.jboss.resteasy.plugins.server.tjws.TJWSEmbeddedJaxrsServer.start(TJWSEmbeddedJaxrsServer.java:58)
	at org.mycontroller.standalone.StartApp.startHTTPWebServer(StartApp.java:236)
        at org.mycontroller.standalone.StartApp.startServices(StartApp.java:323)
	at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:133)
	at org.mycontroller.standalone.StartApp.main(StartApp.java:119)
java.security.ProviderException: Could not initialize NSS
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:223)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.loadAll(ProviderList.java:282)
	at sun.security.jca.ProviderList.removeInvalid(ProviderList.java:299)
	at sun.security.jca.Providers.getFullProviderList(Providers.java:173)
	at java.security.Security.insertProviderAt(Security.java:395)
	at java.security.Security.addProvider(Security.java:438)
	at Acme.Serve.SSLAcceptor.init(SSLAcceptor.java:181)
	at Acme.Serve.Serve.createAcceptor(Serve.java:912)
	at Acme.Serve.Serve.init(Serve.java:769)
	at Acme.Serve.Serve.runInBackground(Serve.java:649)
	at org.jboss.resteasy.plugins.server.tjws.TJWSServletServer.start(TJWSServletServer.java:179)
	at org.jboss.resteasy.plugins.server.tjws.TJWSEmbeddedJaxrsServer.start(TJWSEmbeddedJaxrsServer.java:58)
	at org.mycontroller.standalone.StartApp.startHTTPWebServer(StartApp.java:236)
	at org.mycontroller.standalone.StartApp.startServices(StartApp.java:323)
	at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:133)
	at org.mycontroller.standalone.StartApp.main(StartApp.java:119)
Caused by: java.io.FileNotFoundException: /usr/lib/libnss3.so
	at sun.security.pkcs11.Secmod.initialize(Secmod.java:193)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:218)

	... 25 more
I just started the cointainer with the following: docker run -d -p 1883 -p 8443 --name mycontroller cdrocker/mycontroller

**Comment by kubroid** [comment]
Same here

**Comment by githubcdr** [comment]
Hi, strange I use this image but no issues here.

I'm pushing a new build, can you see if this one works for you?

cDR
